# Generated by Django 3.2.5 on 2021-07-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('NoteId', models.AutoField(primary_key=True, serialize=False)),
                ('NoteText', models.CharField(max_length=2000)),
            ],
        ),
    ]
