# Generated by Django 3.2.5 on 2021-07-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='NoteId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='NoteText',
            new_name='text',
        ),
    ]
