# Generated by Django 3.2.5 on 2021-07-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_auto_20210716_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
