# Generated by Django 3.2.5 on 2021-07-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0004_remove_notes_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='index',
            field=models.BigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
